// The built-in exercise catalogue, shared by the Training tab and Pit Crew.
// Keys must match backend/services/exercise_taxonomy.py EXERCISE_TO_GROUP.

export type Exercise = { key: string; name: string }
export type Group = { name: string; colour: string; exercises: Exercise[] }

export const GROUPS: Group[] = [
  {
    name: 'Chest',
    colour: '#f87171',
    exercises: [
      { key: 'bench_press',           name: 'Bench Press' },
      { key: 'incline_bench',         name: 'Incline Bench' },
      { key: 'decline_bench',         name: 'Decline Bench' },
      { key: 'dumbbell_press',        name: 'Dumbbell Press' },
      { key: 'incline_db_press',      name: 'Incline DB Press' },
      { key: 'decline_db_press',      name: 'Decline DB Press' },
      { key: 'machine_chest_press',   name: 'Machine Chest Press' },
      { key: 'pec_deck',              name: 'Pec Deck' },
      { key: 'chest_fly',             name: 'Chest Fly' },
      { key: 'cable_fly',             name: 'Cable Fly' },
      { key: 'low_cable_fly',         name: 'Low Cable Fly' },
      { key: 'svend_press',           name: 'Svend Press' },
      { key: 'push_up',               name: 'Push-up' },
      { key: 'incline_push_up',       name: 'Incline Push-up' },
      { key: 'deficit_push_up',       name: 'Deficit Push-up' },
      { key: 'chest_dip',             name: 'Chest Dip' },
      { key: 'landmine_press',        name: 'Landmine Press' },
    ],
  },
  {
    name: 'Back',
    colour: '#34d399',
    exercises: [
      { key: 'deadlift',              name: 'Deadlift' },
      { key: 'sumo_deadlift',         name: 'Sumo Deadlift' },
      { key: 'trap_bar_deadlift',     name: 'Trap-bar Deadlift' },
      { key: 'rack_pull',             name: 'Rack Pull' },
      { key: 'barbell_row',           name: 'Barbell Row' },
      { key: 'pendlay_row',           name: 'Pendlay Row' },
      { key: 'seal_row',              name: 'Seal Row' },
      { key: 'tbar_row',              name: 'T-bar Row' },
      { key: 'one_arm_db_row',        name: 'One-arm DB Row' },
      { key: 'meadows_row',           name: 'Meadows Row' },
      { key: 'cable_row',             name: 'Cable Row' },
      { key: 'wide_cable_row',        name: 'Wide-grip Cable Row' },
      { key: 'pull_up',               name: 'Pull-up' },
      { key: 'chin_up',               name: 'Chin-up' },
      { key: 'weighted_pull_up',      name: 'Weighted Pull-up' },
      { key: 'lat_pulldown',          name: 'Lat Pulldown' },
      { key: 'neutral_grip_pulldown', name: 'Neutral-grip Pulldown' },
      { key: 'straight_arm_pulldown', name: 'Straight-arm Pulldown' },
      { key: 'shrug',                 name: 'Shrug' },
      { key: 'db_shrug',              name: 'DB Shrug' },
      { key: 'back_extension',        name: 'Back Extension' },
      { key: 'good_morning',          name: 'Good Morning' },
      { key: 'hip_thrust_back',       name: 'Hip Thrust (back-focus)' },
    ],
  },
  {
    name: 'Legs',
    colour: '#f472b6',
    exercises: [
      { key: 'squat',                 name: 'Back Squat' },
      { key: 'front_squat',           name: 'Front Squat' },
      { key: 'high_bar_squat',        name: 'High-bar Squat' },
      { key: 'low_bar_squat',         name: 'Low-bar Squat' },
      { key: 'box_squat',             name: 'Box Squat' },
      { key: 'pause_squat',           name: 'Pause Squat' },
      { key: 'goblet_squat',          name: 'Goblet Squat' },
      { key: 'bulgarian_split_squat', name: 'Bulgarian Split Squat' },
      { key: 'walking_lunge',         name: 'Walking Lunge' },
      { key: 'reverse_lunge',         name: 'Reverse Lunge' },
      { key: 'step_up',               name: 'Step-up' },
      { key: 'pistol_squat',          name: 'Pistol Squat' },
      { key: 'leg_press',             name: 'Leg Press' },
      { key: 'hack_squat',            name: 'Hack Squat' },
      { key: 'belt_squat',            name: 'Belt Squat' },
      { key: 'romanian_dl',           name: 'Romanian Deadlift' },
      { key: 'stiff_leg_dl',          name: 'Stiff-leg Deadlift' },
      { key: 'single_leg_rdl',        name: 'Single-leg RDL' },
      { key: 'leg_curl',              name: 'Lying Leg Curl' },
      { key: 'seated_leg_curl',       name: 'Seated Leg Curl' },
      { key: 'nordic_curl',           name: 'Nordic Curl' },
      { key: 'leg_extension',         name: 'Leg Extension' },
      { key: 'sissy_squat',           name: 'Sissy Squat' },
      { key: 'hip_thrust',            name: 'Hip Thrust' },
      { key: 'glute_bridge',          name: 'Glute Bridge' },
      { key: 'cable_kickback',        name: 'Cable Kickback' },
      { key: 'hip_abduction',         name: 'Hip Abduction' },
      { key: 'calf_raise',            name: 'Standing Calf Raise' },
      { key: 'seated_calf_raise',     name: 'Seated Calf Raise' },
      { key: 'donkey_calf_raise',     name: 'Donkey Calf Raise' },
    ],
  },
  {
    name: 'Shoulders',
    colour: '#60a5fa',
    exercises: [
      { key: 'overhead_press',        name: 'Overhead Press' },
      { key: 'push_press',            name: 'Push Press' },
      { key: 'seated_ohp',            name: 'Seated OHP' },
      { key: 'db_shoulder_press',     name: 'DB Shoulder Press' },
      { key: 'arnold_press',          name: 'Arnold Press' },
      { key: 'machine_shoulder_press',name: 'Machine Shoulder Press' },
      { key: 'lateral_raise',         name: 'Lateral Raise' },
      { key: 'cable_lateral_raise',   name: 'Cable Lateral Raise' },
      { key: 'leaning_lateral_raise', name: 'Leaning Lateral Raise' },
      { key: 'front_raise',           name: 'Front Raise' },
      { key: 'plate_front_raise',     name: 'Plate Front Raise' },
      { key: 'rear_delt_fly',         name: 'Rear Delt Fly' },
      { key: 'reverse_pec_deck',      name: 'Reverse Pec Deck' },
      { key: 'face_pull',             name: 'Face Pull' },
      { key: 'upright_row',           name: 'Upright Row' },
      { key: 'handstand_push_up',     name: 'Handstand Push-up' },
    ],
  },
  {
    name: 'Arms',
    colour: '#a78bfa',
    exercises: [
      { key: 'bicep_curl',            name: 'Barbell Curl' },
      { key: 'db_curl',               name: 'DB Curl' },
      { key: 'hammer_curl',           name: 'Hammer Curl' },
      { key: 'preacher_curl',         name: 'Preacher Curl' },
      { key: 'incline_db_curl',       name: 'Incline DB Curl' },
      { key: 'cable_curl',            name: 'Cable Curl' },
      { key: 'spider_curl',           name: 'Spider Curl' },
      { key: 'concentration_curl',    name: 'Concentration Curl' },
      { key: 'reverse_curl',          name: 'Reverse Curl' },
      { key: 'zottman_curl',          name: 'Zottman Curl' },
      { key: 'tricep_extension',      name: 'Skullcrusher' },
      { key: 'overhead_tri_extension',name: 'Overhead Tri Extension' },
      { key: 'tricep_pushdown',       name: 'Tricep Pushdown' },
      { key: 'rope_pushdown',         name: 'Rope Pushdown' },
      { key: 'tricep_dip',            name: 'Tricep Dip' },
      { key: 'close_grip_bench',      name: 'Close-grip Bench' },
      { key: 'jm_press',              name: 'JM Press' },
      { key: 'kickback',              name: 'Tricep Kickback' },
      { key: 'wrist_curl',            name: 'Wrist Curl' },
      { key: 'reverse_wrist_curl',    name: 'Reverse Wrist Curl' },
      { key: 'farmer_carry',          name: 'Farmer Carry' },
    ],
  },
  {
    name: 'Core',
    colour: '#facc15',
    exercises: [
      { key: 'plank',                 name: 'Plank' },
      { key: 'side_plank',            name: 'Side Plank' },
      { key: 'cable_crunch',          name: 'Cable Crunch' },
      { key: 'hanging_leg_raise',     name: 'Hanging Leg Raise' },
      { key: 'hanging_knee_raise',    name: 'Hanging Knee Raise' },
      { key: 'ab_wheel',              name: 'Ab Wheel Rollout' },
      { key: 'sit_up',                name: 'Sit-up' },
      { key: 'decline_sit_up',        name: 'Decline Sit-up' },
      { key: 'russian_twist',         name: 'Russian Twist' },
      { key: 'pallof_press',          name: 'Pallof Press' },
      { key: 'wood_chop',             name: 'Cable Wood Chop' },
      { key: 'dead_bug',              name: 'Dead Bug' },
      { key: 'bird_dog',              name: 'Bird Dog' },
      { key: 'l_sit',                 name: 'L-sit Hold' },
      { key: 'dragon_flag',           name: 'Dragon Flag' },
    ],
  },
]

export const ALL_EXERCISES: Exercise[] = GROUPS.flatMap(g => g.exercises)
export const EXERCISE_NAME: Record<string, string> = Object.fromEntries(
  ALL_EXERCISES.map(e => [e.key, e.name]),
)
